spring:
  redis:
    host: @redis.host@
    port: @redis.port@
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0
baidu:
  apikey: CVtbY659ErA3pagRF3KYwVjt
  secretkey: 0boApgKMdtFMCz0pD2AhCePwKgF2ULHU